# SPDX-License-Identifier: GPL-2.0-only

ccflags-y := -Wformat
ccflags-y += $(ccflags-nopmi-base)

obj-$(CONFIG_CHARGER_MAX77729) += max77729_charger.o
obj-$(CONFIG_FUELGAUGE_MAX77729) += max77729_fuelgauge.o
